{{ if and .Values.usePassword (not .Values.existingSecret) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "mongodb.fullname" . }}
  labels:
    app: {{ template "mongodb.name" . }}
    chart: {{ template "mongodb.chart" . }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  {{- if .Values.mongodbHost }}
  db-host:  {{ .Values.mongodbHost | b64enc | quote }}
  {{- else }}
  db-host: {{ randAlphaNum 10 | b64enc | quote }}
  {{- end }}
  {{- if .Values.mongodbPort }}
  db-port:  {{ .Values.mongodbPort | b64enc | quote }}
  {{- else }}
  db-port: {{ randAlphaNum 10 | b64enc | quote }}
  {{- end }}
  {{- if .Values.mongodbDatabase }}
  db-database:  {{ .Values.mongodbDatabase | b64enc | quote }}
  {{- else }}
  db-database: {{ randAlphaNum 10 | b64enc | quote }}
  {{- end }}
  {{- if .Values.mongodbUsername }}
  db-username:  {{ .Values.mongodbUsername | b64enc | quote }}
  {{- else }}
  db-username: {{ randAlphaNum 10 | b64enc | quote }}
  {{- end }}
  {{- if .Values.mongodbPassword }}
  db-password:  {{ .Values.mongodbPassword | b64enc | quote }}
  {{- else }}
  db-password: {{ randAlphaNum 10 | b64enc | quote }}
  {{- end }}
  {{- if .Values.mongodbRootPassword }}
  mongodb-root-password:  {{ .Values.mongodbRootPassword | b64enc | quote }}
  {{- else }}
  mongodb-root-password: {{ randAlphaNum 10 | b64enc | quote }}
  {{- end }}
  {{- if and .Values.mongodbUsername .Values.mongodbDatabase }}
  {{- if .Values.mongodbPassword }}
  mongodb-password:  {{ .Values.mongodbPassword | b64enc | quote }}
  {{- else }}
  mongodb-password: {{ randAlphaNum 10 | b64enc | quote }}
  {{- end }}
  {{- end }}
  {{- if .Values.replicaSet.enabled }}
  {{- if .Values.replicaSet.key }}
  mongodb-replica-set-key:  {{ .Values.replicaSet.key | b64enc | quote }}
  {{- else }}
  mongodb-replica-set-key: {{ randAlphaNum 10 | b64enc | quote }}
  {{- end }}
  {{- end }}
{{- end }}
